<?php

namespace App\Http\Requests\Preoperative;

use Illuminate\Foundation\Http\FormRequest;

class PreoperativeRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'registration' => 'required',
            'mileage' => 'required',
            'trafficlicense' => 'required',
            'mechanicaltechnicalinspection' => '',
            'obligatoryinsurance' => '',
            'thirdpartyinsurance' => '',
            'drivinglicense' => '',
            'routes' => '',
            'emergencycontacts' => '',
            'boots' => '',
            'photoluminescentvest' => '',
            'gloves' => '',
            'hearingprotection' => '',
            'monoglasses' => '',
            'phone' => '',
            'hydration' => '',
            'windshield' => '',
            'wiperwasher' => '',
            'sides' => '',
            'rearglass' => '',
            'lrearwindshield' => '',
            'rearviewmirror' => '',
            'lateralmirrors' => '',
            'cushioncondition' => '',
            'conditionofthechairs' => '',
            'upholsterycondition' => '',
            'vehiclecleaning' => '',
            'doorhandles' => '',
            'doorplates' => '',
            'doorlocks' => '',
            'glasslifter' => '',
            'dooradjustment' => '',
            'horn' => '',
            'reversealarm' => '',
            'instruments' => '',
            'frontsbelts' => '',
            'rearsbelts' => '',
            'electriccontrols' => '',
            'controlpanel' => '',
            'airconditioning' => '',
            'accidentkit' => '',
            'photographiccamera' => '',
            'batterypoweredflashlight' => '',
            'firstaidkit' => '',
            'low' => '',
            'full' => '',
            'directionals' => '',
            'coconuts' => '',
            'reverse' => '',
            'antifog' => '',
            'cabinlights' => '',
            'emergency' => '',
            'thirdstop' => '',
            'engineoil' => '',
            'lastchange' => '',
            'address' => '',
            'brakefluid' => '',
            'refrigerant' => '',
            'windshieldwater' => '',
            'fuellevel' => '',
            'lubricantleaks' => '',
            'waterleaks' => '',
            'securitypin' => '',
            'loaded' => '',
            'current' => '',
            'reflectivetriangles' => '',
            'cat' => '',
            'toolbox' => '',
            'crosspiece' => '',
            'tacos' => '',
            'sparetire' => '',
            'jumpercables' => '',
            'handbrake' => '',
            'fanbelt' => '',
            'mooringdevices' => '',
            'straps' => '',
            'hooks' => '',
            'trailercoupling' => '',
            'wearfrontright' => '',
            'wearleftfront' => '',
            'wearrightrear' => '',
            'wearleftrear' => '',
            'wearsparetire' => '',
            'pressfrontright' => '',
            'pressleftfront' => '',
            'pressrightrear' => '',
            'pressleftrear' => '',
            'presssparetire' => '',
            'observations' => '',
            'vehicle' => 'required',
            'driver' => 'required',
            'status' => '',
        ];
    }

    public function attributes()
    {
        return [
            'registration' => 'Fecha de registro',
            'mileage' => 'Kilometraje',
            'trafficlicense' => 'Licencia de tránsito',
            'mechanicaltechnicalinspection' => 'Revisión técnico mecánica',
            'obligatoryinsurance' => 'Seguro obligatorio',
            'thirdpartyinsurance' => 'Seguro terceros',
            'drivinglicense' => 'Licencia de conducción',
            'routes' => 'Rutas',
            'emergencycontacts' => 'Contactos de Emerge',
            'boots' => 'Botas',
            'photoluminescentvest' => 'Chaleco fotoluminiscente',
            'gloves' => 'Guantes',
            'hearingprotection' => 'Protección auditiva',
            'monoglasses' => 'Monogafas',
            'phone' => 'Radio teléfono, celular',
            'hydration' => 'Hidrata',
            'windshield' => 'Parabrisas',
            'wiperwasher' => 'Limpiaparabrisas',
            'sides' => 'Laterales',
            'rearglass' => 'Vidrio Trasero',
            'lrearwindshield' => 'L/parabrisas trasero',
            'rearviewmirror' => 'Espejo retrovisor',
            'lateralmirrors' => 'Espejos Laterales',
            'cushioncondition' => 'Estado cojinería',
            'conditionofthechairs' => 'Estado de las sillas',
            'upholsterycondition' => 'Estado de la tapicería',
            'vehiclecleaning' => 'Aseo del vehículo.',
            'doorhandles' => 'Manijas puertas',
            'doorplates' => 'Chapas puertas',
            'doorlocks' => 'Seguros puertas',
            'glasslifter' => 'Elevavidrios',
            'dooradjustment' => 'Ajuste de las puertas',
            'horn' => 'Bocina',
            'reversealarm' => 'Alarma reversa',
            'instruments' => 'Instrumentos',
            'frontsbelts' => 'Cinturones S delanteros',
            'rearsbelts' => 'Cinturones S traseros',
            'electriccontrols' => 'Mandos eléctricos',
            'controlpanel' => 'Tablero de controles',
            'airconditioning' => 'Aire acondicionado',
            'accidentkit' => 'Kit de Accidentes ',
            'photographiccamera' => 'Cámara fotográfica',
            'batterypoweredflashlight' => 'Linterna con pilas',
            'firstaidkit' => 'Botiquín',
            'low' => 'Bajas',
            'full' => 'Plenas',
            'directionals' => 'Direccionales',
            'coconuts' => 'Cocullos',
            'reverse' => 'Reversa',
            'antifog' => 'Anti-niebla',
            'cabinlights' => 'Luces de cabina',
            'emergency' => 'Emergencia.',
            'thirdstop' => 'Tercer Stop.',
            'engineoil' => 'Aceite motor',
            'lastchange' => 'Ultimo cambio',
            'address' => 'Dirección ',
            'brakefluid' => 'Líquido de frenos',
            'refrigerant' => 'Refrigerante',
            'windshieldwater' => 'Agua parabrisas',
            'fuellevel' => 'Nivel combustible',
            'lubricantleaks' => 'Fugas de lubricantes',
            'waterleaks' => 'Fugas de Agua',
            'securitypin' => 'Pin de Seguridad',
            'loaded' => 'Cargado',
            'current' => 'Vigente',
            'reflectivetriangles' => 'Triángulos Reflectores',
            'cat' => 'Gato',
            'toolbox' => 'Caja de herramientas.',
            'crosspiece' => 'Cruceta',
            'tacos' => 'Tacos',
            'sparetire' => 'Llanta de repuesto',
            'jumpercables' => 'Freno de mano',
            'handbrake' => 'Correa del Ventilador',
            'fanbelt' => 'Dispositivos de amarre',
            'mooringdevices' => 'Correas',
            'straps' => 'Ganchos',
            'hooks' => 'Gancho de Remolque',
            'trailercoupling' => '',
            'wearfrontright' => 'Delantero Derecho',
            'wearleftfront' => 'Delantero Izquierdo',
            'wearrightrear' => 'Trasero Derecho',
            'wearleftrear' => 'Trasero Izquierdo',
            'wearsparetire' => 'Llanta repuesto',
            'pressfrontright' => 'Delantero Derecho',
            'pressleftfront' => 'Delantero Izquierdo',
            'pressrightrear' => 'Trasero Derecho',
            'pressleftrear' => 'Trasero Izquierdo',
            'presssparetire' => 'Llanta repuesto',
            'observations' => 'Observaciones',
            'vehicle' => 'Vehiculo',
            'driver' => 'Conductor',
            'status' => 'Estado',
        ];
    }
}
