<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Preoperative extends Model
{
    use HasFactory;

    protected $table = 'preoperative';

    protected $primaryKey = 'id';

    protected $fillable = [
        'registration',
        'mileage',
        'trafficlicense',
        'mechanicaltechnicalinspection',
        'obligatoryinsurance',
        'thirdpartyinsurance',
        'drivinglicense',
        'routes',
        'emergencycontacts',
        'boots',
        'photoluminescentvest',
        'gloves',
        'hearingprotection',
        'monoglasses',
        'phone',
        'hydration',
        'windshield',
        'wiperwasher',
        'sides',
        'rearglass',
        'lrearwindshield',
        'rearviewmirror',
        'lateralmirrors',
        'cushioncondition',
        'conditionofthechairs',
        'upholsterycondition',
        'vehiclecleaning',
        'doorhandles',
        'doorplates',
        'doorlocks',
        'glasslifter',
        'dooradjustment',
        'horn',
        'reversealarm',
        'instruments',
        'frontsbelts',
        'rearsbelts',
        'electriccontrols',
        'controlpanel',
        'airconditioning',
        'accidentkit',
        'photographiccamera',
        'batterypoweredflashlight',
        'firstaidkit',
        'low',
        'full',
        'directionals',
        'coconuts',
        'reverse',
        'antifog',
        'cabinlights',
        'emergency',
        'thirdstop',
        'engineoil',
        'lastchange',
        'address',
        'brakefluid',
        'refrigerant',
        'windshieldwater',
        'fuellevel',
        'lubricantleaks',
        'waterleaks',
        'securitypin',
        'loaded',
        'current',
        'reflectivetriangles',
        'cat',
        'toolbox',
        'crosspiece',
        'tacos',
        'sparetire',
        'jumpercables',
        'handbrake',
        'fanbelt',
        'mooringdevices',
        'straps',
        'hooks',
        'trailercoupling',
        'wearfrontright',
        'wearleftfront',
        'wearrightrear',
        'wearleftrear',
        'wearsparetire',
        'pressfrontright',
        'pressleftfront',
        'pressrightrear',
        'pressleftrear',
        'presssparetire',
        'observations',
        'vehicle',
        'driver',
        'status',
    ];
}
